#**Movies** recommended system

**BY- Khushal v pawar**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

Imports required libraries like NumPy, Pandas, Matplotlib, Seaborn, and warnings

In [2]:
df = pd.read_csv('/content/tmdb_5000_movies.csv')
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

Loads the movie dataset CSV file into a dataframe and displays first rows.

In [3]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

Shows all column names in the dataset.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

Displays dataset information like data types and non-null values.

In [5]:
df.shape

(4803, 20)

Shows number of rows and columns in the dataset.

In [6]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

Checks how many missing (null) values are present in each column.

In [7]:
df.duplicated().sum()

np.int64(0)

Checks for duplicate rows in the dataset.

In [8]:
df = df[['title','genres','overview','tagline','vote_average','popularity']]

Selects only important columns like title, genres, overview, etc.

In [9]:
df

,title,genres,overview,tagline,vote_average,popularity
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,7.2,150.437577
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",6.9,139.082615
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,6.3,107.376788
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,The Legend Ends,7.6,112.312950
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","Lost in our world, found in another.",6.1,43.926995
...,...,...,...,...,...,...
4798,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",El Mariachi just wants to play his guitar and ...,"He didn't come looking for trouble, but troubl...",6.6,14.269792
4799,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,5.9,0.642552
4800,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...",NaN,7.0,1.444476
4801,Shanghai Calling,[],When ambitious New York attorney Sam is sent t...,A New Yorker in Shanghai,5.7,0.857008
4802,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]",Ever since the second grade when he first saw ...,NaN,6.3,1.929883

Displays the updated dataframe.

In [10]:
df.isnull().sum()

title             0
genres            0
overview          3
tagline         844
vote_average      0
popularity        0
dtype: int64

Again checks for missing values after filtering columns.

In [11]:
df['overview'] = df['overview'].fillna('')

Replaces missing values in overview column with empty string.

In [12]:
df.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

Displays genres of the first movie.

In [13]:
import ast
df['genres'] = df['genres'].apply(lambda x:[i['name'] for i in ast.literal_eval(x)])

Converts genres from string format to list of genre names

In [14]:
df.head()

,title,genres,overview,tagline,vote_average,popularity
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,7.2,150.437577
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",6.9,139.082615
2,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,6.3,107.376788
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,The Legend Ends,7.6,112.312950
4,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","Lost in our world, found in another.",6.1,43.926995

Shows updated dataframe after processing genres.

In [15]:
df['tagline'] = df['tagline'].fillna('')

Replaces missing values in tagline with empty string

In [16]:
df.isnull().sum()

title           0
genres          0
overview        0
tagline         0
vote_average    0
popularity      0
dtype: int64

Checks missing values again after cleaning.

In [17]:
df['tags'] = df['overview'] + " " + df['tagline'] + " " + df['genres'].apply(lambda x: " ".join(x))

Combines overview, tagline, and genres into a single 'tags' column.

In [18]:
df.head()

,title,genres,overview,tagline,vote_average,popularity,tags
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,7.2,150.437577,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",6.9,139.082615,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,6.3,107.376788,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,The Legend Ends,7.6,112.312950,Following the death of District Attorney Harve...
4,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","Lost in our world, found in another.",6.1,43.926995,"John Carter is a war-weary, former military ca..."

Displays dataframe with new 'tags' column.

In [19]:
df['tags'][1]

'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. At the end of the world, the adventure begins. Adventure Fantasy Action'

Shows tags of second movie.

In [20]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

Imports NLP libraries like nltk, stopwords, lemmatizer, and regex.

In [21]:
nltk.download('stopword')
nltk.download('wordnet')

[nltk_data] Error loading stopword: Package 'stopword' not found in
[nltk_data]     index
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

Downloads necessary NLTK data (stopwords and wordnet).

In [22]:
nltk.download('stopwords')
stop_word=set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

Loads stopwords and initializes lemmatizer.

In [23]:
def process_text(text):
  #lower case
    text = str(text).lower()
    #remove puctuation
    text=re.sub('[^a-zA-Z]',' ',text)
    words=text.split()
    #remove stop word
    words = [word for word in words if word not in stop_word]
    #lemitize
    words=[lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

Defines function to clean text (lowercase, remove symbols, etc.).

In [24]:
df['tags']= df['tags'].apply(process_text)

Applies text preprocessing function to 'tags' column

In [25]:
df['tags'][1]

'captain barbossa long believed dead come back life headed edge earth turner elizabeth swann nothing quite seems end world adventure begin adventure fantasy action'

Displays processed tags of second movie.

In [26]:
df= df.reset_index(drop=True)

Resets dataframe index

In [27]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()

Creates mapping of movie titles to their index.

In [28]:
indices

title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

Displays title-index mapping.

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

Imports TF-IDF vectorizer.

In [30]:
tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1,2),  stop_words='english')

Creates TF-IDF model with specific settings.

In [31]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

Converts text data into numerical TF-IDF vectors.

In [32]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 202932 stored elements and shape (4803, 50000)>

Displays TF-IDF matrix.

In [33]:
def recommend(title, n=10):
    if title not in indices:
        print("Movie not found")
        return

    idx = indices[title]
    sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    sim_idx = sim_score.argsort()[::-1][1:n+1]

    for i in sim_idx:
        print(df['title'].iloc[i])

Defines recommendation function based on similarity.

In [36]:
from sklearn.metrics.pairwise import cosine_similarity
recommend('Spectre',3)

Never Say Never Again
From Russia with Love
Thunderball

Calculates cosine similarity and tests recommendation function.

In [37]:
import pickle
pickle.dump(df,open('tfidf_matrix.pkl','wb'))
pickle.dump(df.to_dict(),open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))

Saves dataframe and model using pickle for future use.